app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_registration:
    path: /register/
    defaults: { _controller: AppBundle:Registration:register }

login:
    path: /login/
    defaults: { _controller: AppBundle:Authentication:login}

login_check:
    path: /login_check

user_project:
    path: /project/new/
    defaults: { _controller: AppBundle:Project:new }

show_project:
    path: /project/viewDetails/{id}
    defaults: { _controller: AppBundle:Project:viewDetails}
    requirements:
        id:  \d+

parse_project:
    path: /project/parse/
    defaults: { _controller: AppBundle:Project:parseFile }